package org.zoomdev.zoom.dao.impl;

import org.codehaus.jackson.map.ObjectMapper;
import org.zoomdev.zoom.common.caster.Caster;
import org.zoomdev.zoom.dao.adapters.EntityField;
import org.zoomdev.zoom.dao.utils.DaoUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ZoomAutoEntity implements AutoEntity {
    private String[] autoGeneratedKeys;
    private EntityField[] entityFields;

    public ZoomAutoEntity(String[] autoGeneratedKeys, EntityField[] entityFields) {
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.entityFields = entityFields;
    }

    @Override
    public PreparedStatement prepareInsert(Connection connection, String sql) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public void afterInsert(Object data, PreparedStatement ps) throws SQLException {
        ResultSet rs = null;
        try {
            rs = ps.getGeneratedKeys();
            if (rs.next()) {
                int index = 1;
                for (EntityField entityField : entityFields) {
                    // 注意这里有个坑，GenerateKey生成的数据，类型可能与数据库MetaData的不一致。
                    Object value = entityField.getFieldValue(rs.getObject(index++));
                    if(entityField.getFieldType()==null){
                        entityField.set(data,value );
                    }else{
                        entityField.set(data, Caster.toType(value,entityField.getFieldType()));
                    }

                }
            } else {
                //  log.error("自动生成的字段没有生成成功" + entityField.getTable());
            }
        } finally {
            DaoUtils.close(rs);
        }
    }
}
