language: java

sudo: required

services:
  - mysql

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - mysql -e 'create database zoom;'
  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -u root -e "GRANT ALL ON zoom.* TO 'zoom'@'localhost';"

after_success:
  - mvn jacoco:report coveralls:report

script: mvn clean test

cache:
  directories:
    - $HOME/.m2
