language: java

sudo: required

services:
  - mysql

jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

dist: trusty

env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE


#  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart

after_success:
  - mvn jacoco:report coveralls:report

script: mvn clean test

cache:
  directories:
    - $HOME/.m2
