language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE

before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh

after_success:
  - mvn jacoco:report coveralls:report

script: mvn clean test

cache:
  directories:
    - $HOME/.m2
