language: java
sudo: false
service: docker

jdk:
  - oraclejdk8

install:
  - ./boot/database/oracle/install.sh

after_success:
  - mvn jacoco:report coveralls:report

script: mvn clean test

cache:
  directories:
    - $HOME/.m2
