package com.jzoom.zoom.web.classloader;

/**
 * Hold classes generated by aop
 * @author jzoom
 *
 */
public class WebClassLoader extends ClassLoader {

	public WebClassLoader(ClassLoader parent) {
		super(parent);
	}
	
	@Override
	public String toString() {
		return "WebClassLoader";
	}
	
}
