package com.jzoom.zoom.dao.impl;

import com.jzoom.zoom.dao.adapters.EntityField;
import com.jzoom.zoom.dao.utils.DaoUtils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class ZoomAutoEntity implements AutoEntity{
    private String[] autoGeneratedKeys;
    private EntityField[] entityFields;

    public ZoomAutoEntity(String[] autoGeneratedKeys, EntityField[] entityFields) {
        this.autoGeneratedKeys = autoGeneratedKeys;
        this.entityFields = entityFields;
    }

    @Override
    public PreparedStatement prepareInsert(Connection connection, String sql) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    @Override
    public void afterInsert(Object data, PreparedStatement ps) throws SQLException {
        ResultSet rs = null;
        try {
            rs = ps.getGeneratedKeys();
            if (rs.next()) {
                int index = 1;
                for (EntityField entityField : entityFields) {
                    entityField.set(data, entityField.getFieldValue(rs.getObject(index++)));
                }
            } else {
                //  log.error("自动生成的字段没有生成成功" + entityField.getTable());
            }
        } finally {
            DaoUtils.close(rs);
        }
    }
}
